/**
 * Seed S&P 500 tickers + extended crypto, sector ETFs, and macro indices
 * Run with: npx tsx scripts/seed-sp500-tickers.ts
 *
 * Deduplicates against existing tickers before inserting.
 * Uses Supabase directly for reliability (no API dependency).
 */

import { createClient } from "@supabase/supabase-js";

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY!;

if (!supabaseUrl || !supabaseKey) {
  console.error("Set NEXT_PUBLIC_SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY");
  process.exit(1);
}

const supabase = createClient(supabaseUrl, supabaseKey);

interface TickerSeed {
  symbol: string;
  name: string;
  asset_class: string;
  aliases?: string[];
}

// S&P 500 constituents (static as of Q1 2025 — changes quarterly)
const SP500: TickerSeed[] = [
  // Information Technology
  { symbol: "AAPL", name: "Apple Inc", asset_class: "equities" },
  { symbol: "MSFT", name: "Microsoft Corporation", asset_class: "equities" },
  { symbol: "NVDA", name: "NVIDIA Corporation", asset_class: "equities" },
  { symbol: "AVGO", name: "Broadcom Inc", asset_class: "equities" },
  { symbol: "ORCL", name: "Oracle Corporation", asset_class: "equities" },
  { symbol: "CRM", name: "Salesforce Inc", asset_class: "equities" },
  { symbol: "AMD", name: "Advanced Micro Devices", asset_class: "equities" },
  { symbol: "CSCO", name: "Cisco Systems", asset_class: "equities" },
  { symbol: "ACN", name: "Accenture plc", asset_class: "equities" },
  { symbol: "ADBE", name: "Adobe Inc", asset_class: "equities" },
  { symbol: "IBM", name: "IBM Corporation", asset_class: "equities" },
  { symbol: "TXN", name: "Texas Instruments", asset_class: "equities" },
  { symbol: "INTU", name: "Intuit Inc", asset_class: "equities" },
  { symbol: "QCOM", name: "Qualcomm Inc", asset_class: "equities" },
  { symbol: "AMAT", name: "Applied Materials", asset_class: "equities" },
  { symbol: "NOW", name: "ServiceNow Inc", asset_class: "equities" },
  { symbol: "PANW", name: "Palo Alto Networks", asset_class: "equities" },
  { symbol: "ADI", name: "Analog Devices", asset_class: "equities" },
  { symbol: "MU", name: "Micron Technology", asset_class: "equities" },
  { symbol: "LRCX", name: "Lam Research", asset_class: "equities" },
  { symbol: "KLAC", name: "KLA Corporation", asset_class: "equities" },
  { symbol: "SNPS", name: "Synopsys Inc", asset_class: "equities" },
  { symbol: "CDNS", name: "Cadence Design Systems", asset_class: "equities" },
  { symbol: "CRWD", name: "CrowdStrike Holdings", asset_class: "equities" },
  { symbol: "MSI", name: "Motorola Solutions", asset_class: "equities" },
  { symbol: "FTNT", name: "Fortinet Inc", asset_class: "equities" },
  { symbol: "MCHP", name: "Microchip Technology", asset_class: "equities" },
  { symbol: "ON", name: "ON Semiconductor", asset_class: "equities" },
  { symbol: "IT", name: "Gartner Inc", asset_class: "equities" },
  { symbol: "NXPI", name: "NXP Semiconductors", asset_class: "equities" },
  { symbol: "HPQ", name: "HP Inc", asset_class: "equities" },
  { symbol: "HPE", name: "Hewlett Packard Enterprise", asset_class: "equities" },
  { symbol: "KEYS", name: "Keysight Technologies", asset_class: "equities" },
  { symbol: "MPWR", name: "Monolithic Power Systems", asset_class: "equities" },
  { symbol: "FSLR", name: "First Solar Inc", asset_class: "equities" },
  { symbol: "GEN", name: "Gen Digital Inc", asset_class: "equities" },
  { symbol: "EPAM", name: "EPAM Systems", asset_class: "equities" },
  { symbol: "ZBRA", name: "Zebra Technologies", asset_class: "equities" },
  { symbol: "TRMB", name: "Trimble Inc", asset_class: "equities" },
  { symbol: "TDY", name: "Teledyne Technologies", asset_class: "equities" },
  { symbol: "SWKS", name: "Skyworks Solutions", asset_class: "equities" },
  { symbol: "TER", name: "Teradyne Inc", asset_class: "equities" },
  { symbol: "NTAP", name: "NetApp Inc", asset_class: "equities" },
  { symbol: "JNPR", name: "Juniper Networks", asset_class: "equities" },
  { symbol: "PTC", name: "PTC Inc", asset_class: "equities" },
  { symbol: "FFIV", name: "F5 Inc", asset_class: "equities" },
  { symbol: "AKAM", name: "Akamai Technologies", asset_class: "equities" },
  // Communication Services
  { symbol: "META", name: "Meta Platforms", asset_class: "equities" },
  { symbol: "GOOGL", name: "Alphabet Inc Class A", asset_class: "equities" },
  { symbol: "GOOG", name: "Alphabet Inc Class C", asset_class: "equities" },
  { symbol: "NFLX", name: "Netflix Inc", asset_class: "equities" },
  { symbol: "DIS", name: "Walt Disney Company", asset_class: "equities" },
  { symbol: "CMCSA", name: "Comcast Corporation", asset_class: "equities" },
  { symbol: "TMUS", name: "T-Mobile US", asset_class: "equities" },
  { symbol: "VZ", name: "Verizon Communications", asset_class: "equities" },
  { symbol: "T", name: "AT&T Inc", asset_class: "equities" },
  { symbol: "CHTR", name: "Charter Communications", asset_class: "equities" },
  { symbol: "EA", name: "Electronic Arts", asset_class: "equities" },
  { symbol: "WBD", name: "Warner Bros Discovery", asset_class: "equities" },
  { symbol: "OMC", name: "Omnicom Group", asset_class: "equities" },
  { symbol: "TTWO", name: "Take-Two Interactive", asset_class: "equities" },
  { symbol: "LYV", name: "Live Nation Entertainment", asset_class: "equities" },
  { symbol: "IPG", name: "Interpublic Group", asset_class: "equities" },
  { symbol: "MTCH", name: "Match Group", asset_class: "equities" },
  { symbol: "PARA", name: "Paramount Global", asset_class: "equities" },
  { symbol: "FOXA", name: "Fox Corporation Class A", asset_class: "equities" },
  { symbol: "FOX", name: "Fox Corporation Class B", asset_class: "equities" },
  { symbol: "NWS", name: "News Corp Class B", asset_class: "equities" },
  { symbol: "NWSA", name: "News Corp Class A", asset_class: "equities" },
  // Consumer Discretionary
  { symbol: "AMZN", name: "Amazon.com Inc", asset_class: "equities" },
  { symbol: "TSLA", name: "Tesla Inc", asset_class: "equities" },
  { symbol: "HD", name: "Home Depot", asset_class: "equities" },
  { symbol: "MCD", name: "McDonald's Corporation", asset_class: "equities" },
  { symbol: "LOW", name: "Lowe's Companies", asset_class: "equities" },
  { symbol: "BKNG", name: "Booking Holdings", asset_class: "equities" },
  { symbol: "TJX", name: "TJX Companies", asset_class: "equities" },
  { symbol: "NKE", name: "Nike Inc", asset_class: "equities" },
  { symbol: "SBUX", name: "Starbucks Corporation", asset_class: "equities" },
  { symbol: "ABNB", name: "Airbnb Inc", asset_class: "equities" },
  { symbol: "ORLY", name: "O'Reilly Automotive", asset_class: "equities" },
  { symbol: "AZO", name: "AutoZone Inc", asset_class: "equities" },
  { symbol: "MAR", name: "Marriott International", asset_class: "equities" },
  { symbol: "CMG", name: "Chipotle Mexican Grill", asset_class: "equities" },
  { symbol: "GM", name: "General Motors", asset_class: "equities" },
  { symbol: "ROST", name: "Ross Stores", asset_class: "equities" },
  { symbol: "F", name: "Ford Motor Company", asset_class: "equities" },
  { symbol: "DHI", name: "D.R. Horton", asset_class: "equities" },
  { symbol: "LEN", name: "Lennar Corporation", asset_class: "equities" },
  { symbol: "HLT", name: "Hilton Worldwide", asset_class: "equities" },
  { symbol: "YUM", name: "Yum! Brands", asset_class: "equities" },
  { symbol: "ULTA", name: "Ulta Beauty", asset_class: "equities" },
  { symbol: "DECK", name: "Deckers Outdoor", asset_class: "equities" },
  { symbol: "GPC", name: "Genuine Parts Company", asset_class: "equities" },
  { symbol: "EBAY", name: "eBay Inc", asset_class: "equities" },
  { symbol: "POOL", name: "Pool Corporation", asset_class: "equities" },
  { symbol: "PHM", name: "PulteGroup Inc", asset_class: "equities" },
  { symbol: "DPZ", name: "Domino's Pizza", asset_class: "equities" },
  { symbol: "RCL", name: "Royal Caribbean", asset_class: "equities" },
  { symbol: "CCL", name: "Carnival Corporation", asset_class: "equities" },
  { symbol: "EXPE", name: "Expedia Group", asset_class: "equities" },
  { symbol: "DARDEN", name: "Darden Restaurants", asset_class: "equities" },
  { symbol: "BBY", name: "Best Buy", asset_class: "equities" },
  { symbol: "LVS", name: "Las Vegas Sands", asset_class: "equities" },
  { symbol: "WYNN", name: "Wynn Resorts", asset_class: "equities" },
  { symbol: "MGM", name: "MGM Resorts", asset_class: "equities" },
  { symbol: "NVR", name: "NVR Inc", asset_class: "equities" },
  { symbol: "TPR", name: "Tapestry Inc", asset_class: "equities" },
  { symbol: "BWA", name: "BorgWarner Inc", asset_class: "equities" },
  { symbol: "APTV", name: "Aptiv PLC", asset_class: "equities" },
  { symbol: "CZR", name: "Caesars Entertainment", asset_class: "equities" },
  { symbol: "GRMN", name: "Garmin Ltd", asset_class: "equities" },
  { symbol: "KMX", name: "CarMax Inc", asset_class: "equities" },
  { symbol: "ETSY", name: "Etsy Inc", asset_class: "equities" },
  { symbol: "RL", name: "Ralph Lauren", asset_class: "equities" },
  { symbol: "HAS", name: "Hasbro Inc", asset_class: "equities" },
  { symbol: "MHK", name: "Mohawk Industries", asset_class: "equities" },
  // Health Care
  { symbol: "LLY", name: "Eli Lilly", asset_class: "equities" },
  { symbol: "UNH", name: "UnitedHealth Group", asset_class: "equities" },
  { symbol: "JNJ", name: "Johnson & Johnson", asset_class: "equities" },
  { symbol: "ABBV", name: "AbbVie Inc", asset_class: "equities" },
  { symbol: "MRK", name: "Merck & Co", asset_class: "equities" },
  { symbol: "TMO", name: "Thermo Fisher Scientific", asset_class: "equities" },
  { symbol: "ABT", name: "Abbott Laboratories", asset_class: "equities" },
  { symbol: "DHR", name: "Danaher Corporation", asset_class: "equities" },
  { symbol: "PFE", name: "Pfizer Inc", asset_class: "equities" },
  { symbol: "AMGN", name: "Amgen Inc", asset_class: "equities" },
  { symbol: "SYK", name: "Stryker Corporation", asset_class: "equities" },
  { symbol: "ISRG", name: "Intuitive Surgical", asset_class: "equities" },
  { symbol: "BMY", name: "Bristol-Myers Squibb", asset_class: "equities" },
  { symbol: "VRTX", name: "Vertex Pharmaceuticals", asset_class: "equities" },
  { symbol: "MDT", name: "Medtronic plc", asset_class: "equities" },
  { symbol: "GILD", name: "Gilead Sciences", asset_class: "equities" },
  { symbol: "REGN", name: "Regeneron Pharmaceuticals", asset_class: "equities" },
  { symbol: "ELV", name: "Elevance Health", asset_class: "equities" },
  { symbol: "CI", name: "Cigna Group", asset_class: "equities" },
  { symbol: "BSX", name: "Boston Scientific", asset_class: "equities" },
  { symbol: "ZTS", name: "Zoetis Inc", asset_class: "equities" },
  { symbol: "HCA", name: "HCA Healthcare", asset_class: "equities" },
  { symbol: "EW", name: "Edwards Lifesciences", asset_class: "equities" },
  { symbol: "IQV", name: "IQVIA Holdings", asset_class: "equities" },
  { symbol: "MCK", name: "McKesson Corporation", asset_class: "equities" },
  { symbol: "A", name: "Agilent Technologies", asset_class: "equities" },
  { symbol: "BDX", name: "Becton Dickinson", asset_class: "equities" },
  { symbol: "RMD", name: "ResMed Inc", asset_class: "equities" },
  { symbol: "IDXX", name: "IDEXX Laboratories", asset_class: "equities" },
  { symbol: "MTD", name: "Mettler-Toledo", asset_class: "equities" },
  { symbol: "DXCM", name: "DexCom Inc", asset_class: "equities" },
  { symbol: "GEHC", name: "GE HealthCare Technologies", asset_class: "equities" },
  { symbol: "WAT", name: "Waters Corporation", asset_class: "equities" },
  { symbol: "HOLX", name: "Hologic Inc", asset_class: "equities" },
  { symbol: "ALGN", name: "Align Technology", asset_class: "equities" },
  { symbol: "MOH", name: "Molina Healthcare", asset_class: "equities" },
  { symbol: "CNC", name: "Centene Corporation", asset_class: "equities" },
  { symbol: "BIIB", name: "Biogen Inc", asset_class: "equities" },
  { symbol: "MRNA", name: "Moderna Inc", asset_class: "equities" },
  { symbol: "CAH", name: "Cardinal Health", asset_class: "equities" },
  { symbol: "COR", name: "Cencora Inc", asset_class: "equities" },
  { symbol: "ILMN", name: "Illumina Inc", asset_class: "equities" },
  { symbol: "INCY", name: "Incyte Corporation", asset_class: "equities" },
  { symbol: "TECH", name: "Bio-Techne Corporation", asset_class: "equities" },
  { symbol: "VTRS", name: "Viatris Inc", asset_class: "equities" },
  { symbol: "DVA", name: "DaVita Inc", asset_class: "equities" },
  // Financials
  { symbol: "BRK.B", name: "Berkshire Hathaway", asset_class: "equities" },
  { symbol: "JPM", name: "JPMorgan Chase", asset_class: "equities" },
  { symbol: "V", name: "Visa Inc", asset_class: "equities" },
  { symbol: "MA", name: "Mastercard Inc", asset_class: "equities" },
  { symbol: "BAC", name: "Bank of America", asset_class: "equities" },
  { symbol: "WFC", name: "Wells Fargo", asset_class: "equities" },
  { symbol: "GS", name: "Goldman Sachs", asset_class: "equities" },
  { symbol: "MS", name: "Morgan Stanley", asset_class: "equities" },
  { symbol: "SPGI", name: "S&P Global", asset_class: "equities" },
  { symbol: "AXP", name: "American Express", asset_class: "equities" },
  { symbol: "BLK", name: "BlackRock Inc", asset_class: "equities" },
  { symbol: "C", name: "Citigroup Inc", asset_class: "equities" },
  { symbol: "SCHW", name: "Charles Schwab", asset_class: "equities" },
  { symbol: "CB", name: "Chubb Limited", asset_class: "equities" },
  { symbol: "MMC", name: "Marsh & McLennan", asset_class: "equities" },
  { symbol: "PGR", name: "Progressive Corporation", asset_class: "equities" },
  { symbol: "ICE", name: "Intercontinental Exchange", asset_class: "equities" },
  { symbol: "CME", name: "CME Group", asset_class: "equities" },
  { symbol: "AON", name: "Aon plc", asset_class: "equities" },
  { symbol: "MCO", name: "Moody's Corporation", asset_class: "equities" },
  { symbol: "USB", name: "US Bancorp", asset_class: "equities" },
  { symbol: "PNC", name: "PNC Financial", asset_class: "equities" },
  { symbol: "AJG", name: "Arthur J. Gallagher", asset_class: "equities" },
  { symbol: "TFC", name: "Truist Financial", asset_class: "equities" },
  { symbol: "MET", name: "MetLife Inc", asset_class: "equities" },
  { symbol: "AFL", name: "Aflac Inc", asset_class: "equities" },
  { symbol: "AIG", name: "American International Group", asset_class: "equities" },
  { symbol: "ALL", name: "Allstate Corporation", asset_class: "equities" },
  { symbol: "PRU", name: "Prudential Financial", asset_class: "equities" },
  { symbol: "TRV", name: "Travelers Companies", asset_class: "equities" },
  { symbol: "FIS", name: "Fidelity National Info", asset_class: "equities" },
  { symbol: "MSCI", name: "MSCI Inc", asset_class: "equities" },
  { symbol: "COF", name: "Capital One Financial", asset_class: "equities" },
  { symbol: "BK", name: "Bank of New York Mellon", asset_class: "equities" },
  { symbol: "STT", name: "State Street Corporation", asset_class: "equities" },
  { symbol: "FITB", name: "Fifth Third Bancorp", asset_class: "equities" },
  { symbol: "MTB", name: "M&T Bank Corporation", asset_class: "equities" },
  { symbol: "KEY", name: "KeyCorp", asset_class: "equities" },
  { symbol: "HBAN", name: "Huntington Bancshares", asset_class: "equities" },
  { symbol: "RF", name: "Regions Financial", asset_class: "equities" },
  { symbol: "CFG", name: "Citizens Financial", asset_class: "equities" },
  { symbol: "NTRS", name: "Northern Trust", asset_class: "equities" },
  { symbol: "NDAQ", name: "Nasdaq Inc", asset_class: "equities" },
  { symbol: "CBOE", name: "Cboe Global Markets", asset_class: "equities" },
  { symbol: "CINF", name: "Cincinnati Financial", asset_class: "equities" },
  { symbol: "BRO", name: "Brown & Brown", asset_class: "equities" },
  { symbol: "RJF", name: "Raymond James Financial", asset_class: "equities" },
  { symbol: "TROW", name: "T. Rowe Price", asset_class: "equities" },
  { symbol: "SYF", name: "Synchrony Financial", asset_class: "equities" },
  { symbol: "DFS", name: "Discover Financial", asset_class: "equities" },
  { symbol: "WRB", name: "W. R. Berkley", asset_class: "equities" },
  { symbol: "BEN", name: "Franklin Resources", asset_class: "equities" },
  { symbol: "IVZ", name: "Invesco Ltd", asset_class: "equities" },
  { symbol: "MKTX", name: "MarketAxess Holdings", asset_class: "equities" },
  { symbol: "GL", name: "Globe Life Inc", asset_class: "equities" },
  { symbol: "L", name: "Loews Corporation", asset_class: "equities" },
  { symbol: "RE", name: "Everest Group", asset_class: "equities" },
  // Industrials
  { symbol: "GE", name: "GE Aerospace", asset_class: "equities" },
  { symbol: "CAT", name: "Caterpillar Inc", asset_class: "equities" },
  { symbol: "RTX", name: "RTX Corporation", asset_class: "equities" },
  { symbol: "HON", name: "Honeywell International", asset_class: "equities" },
  { symbol: "UNP", name: "Union Pacific", asset_class: "equities" },
  { symbol: "BA", name: "Boeing Company", asset_class: "equities" },
  { symbol: "DE", name: "Deere & Company", asset_class: "equities" },
  { symbol: "LMT", name: "Lockheed Martin", asset_class: "equities" },
  { symbol: "UPS", name: "United Parcel Service", asset_class: "equities" },
  { symbol: "ADP", name: "Automatic Data Processing", asset_class: "equities" },
  { symbol: "ETN", name: "Eaton Corporation", asset_class: "equities" },
  { symbol: "WM", name: "Waste Management", asset_class: "equities" },
  { symbol: "NOC", name: "Northrop Grumman", asset_class: "equities" },
  { symbol: "GD", name: "General Dynamics", asset_class: "equities" },
  { symbol: "ITW", name: "Illinois Tool Works", asset_class: "equities" },
  { symbol: "CSX", name: "CSX Corporation", asset_class: "equities" },
  { symbol: "NSC", name: "Norfolk Southern", asset_class: "equities" },
  { symbol: "EMR", name: "Emerson Electric", asset_class: "equities" },
  { symbol: "FDX", name: "FedEx Corporation", asset_class: "equities" },
  { symbol: "MMM", name: "3M Company", asset_class: "equities" },
  { symbol: "PH", name: "Parker-Hannifin", asset_class: "equities" },
  { symbol: "CTAS", name: "Cintas Corporation", asset_class: "equities" },
  { symbol: "CARR", name: "Carrier Global", asset_class: "equities" },
  { symbol: "TT", name: "Trane Technologies", asset_class: "equities" },
  { symbol: "PCAR", name: "PACCAR Inc", asset_class: "equities" },
  { symbol: "FAST", name: "Fastenal Company", asset_class: "equities" },
  { symbol: "RSG", name: "Republic Services", asset_class: "equities" },
  { symbol: "OTIS", name: "Otis Worldwide", asset_class: "equities" },
  { symbol: "AME", name: "AMETEK Inc", asset_class: "equities" },
  { symbol: "VRSK", name: "Verisk Analytics", asset_class: "equities" },
  { symbol: "GWW", name: "W.W. Grainger", asset_class: "equities" },
  { symbol: "PWR", name: "Quanta Services", asset_class: "equities" },
  { symbol: "PAYX", name: "Paychex Inc", asset_class: "equities" },
  { symbol: "CPRT", name: "Copart Inc", asset_class: "equities" },
  { symbol: "ROK", name: "Rockwell Automation", asset_class: "equities" },
  { symbol: "XYL", name: "Xylem Inc", asset_class: "equities" },
  { symbol: "WAB", name: "Westinghouse Air Brake", asset_class: "equities" },
  { symbol: "HUBB", name: "Hubbell Inc", asset_class: "equities" },
  { symbol: "DOV", name: "Dover Corporation", asset_class: "equities" },
  { symbol: "SWK", name: "Stanley Black & Decker", asset_class: "equities" },
  { symbol: "IEX", name: "IDEX Corporation", asset_class: "equities" },
  { symbol: "DAY", name: "Dayforce Inc", asset_class: "equities" },
  { symbol: "AXON", name: "Axon Enterprise", asset_class: "equities" },
  { symbol: "IR", name: "Ingersoll Rand", asset_class: "equities" },
  { symbol: "J", name: "Jacobs Solutions", asset_class: "equities" },
  { symbol: "LDOS", name: "Leidos Holdings", asset_class: "equities" },
  { symbol: "NDSN", name: "Nordson Corporation", asset_class: "equities" },
  { symbol: "GNRC", name: "Generac Holdings", asset_class: "equities" },
  { symbol: "EFX", name: "Equifax Inc", asset_class: "equities" },
  // Consumer Staples
  { symbol: "PG", name: "Procter & Gamble", asset_class: "equities" },
  { symbol: "KO", name: "Coca-Cola Company", asset_class: "equities" },
  { symbol: "PEP", name: "PepsiCo Inc", asset_class: "equities" },
  { symbol: "COST", name: "Costco Wholesale", asset_class: "equities" },
  { symbol: "PM", name: "Philip Morris International", asset_class: "equities" },
  { symbol: "WMT", name: "Walmart Inc", asset_class: "equities" },
  { symbol: "MO", name: "Altria Group", asset_class: "equities" },
  { symbol: "MDLZ", name: "Mondelez International", asset_class: "equities" },
  { symbol: "CL", name: "Colgate-Palmolive", asset_class: "equities" },
  { symbol: "TGT", name: "Target Corporation", asset_class: "equities" },
  { symbol: "ADM", name: "Archer-Daniels-Midland", asset_class: "equities" },
  { symbol: "STZ", name: "Constellation Brands", asset_class: "equities" },
  { symbol: "GIS", name: "General Mills", asset_class: "equities" },
  { symbol: "SYY", name: "Sysco Corporation", asset_class: "equities" },
  { symbol: "HSY", name: "Hershey Company", asset_class: "equities" },
  { symbol: "KMB", name: "Kimberly-Clark", asset_class: "equities" },
  { symbol: "MKC", name: "McCormick & Company", asset_class: "equities" },
  { symbol: "K", name: "Kellanova", asset_class: "equities" },
  { symbol: "KHC", name: "Kraft Heinz", asset_class: "equities" },
  { symbol: "MNST", name: "Monster Beverage", asset_class: "equities" },
  { symbol: "KDP", name: "Keurig Dr Pepper", asset_class: "equities" },
  { symbol: "EL", name: "Estee Lauder", asset_class: "equities" },
  { symbol: "CAG", name: "Conagra Brands", asset_class: "equities" },
  { symbol: "CHD", name: "Church & Dwight", asset_class: "equities" },
  { symbol: "CLX", name: "Clorox Company", asset_class: "equities" },
  { symbol: "SJM", name: "J.M. Smucker", asset_class: "equities" },
  { symbol: "TSN", name: "Tyson Foods", asset_class: "equities" },
  { symbol: "HRL", name: "Hormel Foods", asset_class: "equities" },
  { symbol: "TAP", name: "Molson Coors", asset_class: "equities" },
  { symbol: "CPB", name: "Campbell Soup", asset_class: "equities" },
  { symbol: "LW", name: "Lamb Weston", asset_class: "equities" },
  { symbol: "BG", name: "Bunge Global", asset_class: "equities" },
  // Energy
  { symbol: "XOM", name: "Exxon Mobil", asset_class: "equities" },
  { symbol: "CVX", name: "Chevron Corporation", asset_class: "equities" },
  { symbol: "COP", name: "ConocoPhillips", asset_class: "equities" },
  { symbol: "SLB", name: "Schlumberger Ltd", asset_class: "equities" },
  { symbol: "EOG", name: "EOG Resources", asset_class: "equities" },
  { symbol: "MPC", name: "Marathon Petroleum", asset_class: "equities" },
  { symbol: "PSX", name: "Phillips 66", asset_class: "equities" },
  { symbol: "PXD", name: "Pioneer Natural Resources", asset_class: "equities" },
  { symbol: "VLO", name: "Valero Energy", asset_class: "equities" },
  { symbol: "WMB", name: "Williams Companies", asset_class: "equities" },
  { symbol: "OKE", name: "ONEOK Inc", asset_class: "equities" },
  { symbol: "KMI", name: "Kinder Morgan", asset_class: "equities" },
  { symbol: "HAL", name: "Halliburton Company", asset_class: "equities" },
  { symbol: "BKR", name: "Baker Hughes", asset_class: "equities" },
  { symbol: "FANG", name: "Diamondback Energy", asset_class: "equities" },
  { symbol: "DVN", name: "Devon Energy", asset_class: "equities" },
  { symbol: "HES", name: "Hess Corporation", asset_class: "equities" },
  { symbol: "TRGP", name: "Targa Resources", asset_class: "equities" },
  { symbol: "OXY", name: "Occidental Petroleum", asset_class: "equities" },
  { symbol: "CTRA", name: "Coterra Energy", asset_class: "equities" },
  { symbol: "MRO", name: "Marathon Oil", asset_class: "equities" },
  { symbol: "APA", name: "APA Corporation", asset_class: "equities" },
  // Materials
  { symbol: "LIN", name: "Linde plc", asset_class: "equities" },
  { symbol: "APD", name: "Air Products", asset_class: "equities" },
  { symbol: "SHW", name: "Sherwin-Williams", asset_class: "equities" },
  { symbol: "FCX", name: "Freeport-McMoRan", asset_class: "equities" },
  { symbol: "ECL", name: "Ecolab Inc", asset_class: "equities" },
  { symbol: "NUE", name: "Nucor Corporation", asset_class: "equities" },
  { symbol: "DOW", name: "Dow Inc", asset_class: "equities" },
  { symbol: "DD", name: "DuPont de Nemours", asset_class: "equities" },
  { symbol: "PPG", name: "PPG Industries", asset_class: "equities" },
  { symbol: "VMC", name: "Vulcan Materials", asset_class: "equities" },
  { symbol: "MLM", name: "Martin Marietta", asset_class: "equities" },
  { symbol: "CTVA", name: "Corteva Agriscience", asset_class: "equities" },
  { symbol: "ALB", name: "Albemarle Corporation", asset_class: "equities" },
  { symbol: "EMN", name: "Eastman Chemical", asset_class: "equities" },
  { symbol: "PKG", name: "Packaging Corp of America", asset_class: "equities" },
  { symbol: "IP", name: "International Paper", asset_class: "equities" },
  { symbol: "CF", name: "CF Industries", asset_class: "equities" },
  { symbol: "IFF", name: "International Flavors", asset_class: "equities" },
  { symbol: "CE", name: "Celanese Corporation", asset_class: "equities" },
  { symbol: "BALL", name: "Ball Corporation", asset_class: "equities" },
  { symbol: "AVY", name: "Avery Dennison", asset_class: "equities" },
  { symbol: "AMCR", name: "Amcor plc", asset_class: "equities" },
  { symbol: "MOS", name: "Mosaic Company", asset_class: "equities" },
  { symbol: "FMC", name: "FMC Corporation", asset_class: "equities" },
  { symbol: "SEE", name: "Sealed Air Corporation", asset_class: "equities" },
  // Utilities
  { symbol: "NEE", name: "NextEra Energy", asset_class: "equities" },
  { symbol: "SO", name: "Southern Company", asset_class: "equities" },
  { symbol: "DUK", name: "Duke Energy", asset_class: "equities" },
  { symbol: "SRE", name: "Sempra", asset_class: "equities" },
  { symbol: "AEP", name: "American Electric Power", asset_class: "equities" },
  { symbol: "D", name: "Dominion Energy", asset_class: "equities" },
  { symbol: "EXC", name: "Exelon Corporation", asset_class: "equities" },
  { symbol: "XEL", name: "Xcel Energy", asset_class: "equities" },
  { symbol: "ED", name: "Consolidated Edison", asset_class: "equities" },
  { symbol: "PEG", name: "Public Service Enterprise", asset_class: "equities" },
  { symbol: "WEC", name: "WEC Energy Group", asset_class: "equities" },
  { symbol: "AWK", name: "American Water Works", asset_class: "equities" },
  { symbol: "DTE", name: "DTE Energy", asset_class: "equities" },
  { symbol: "ES", name: "Eversource Energy", asset_class: "equities" },
  { symbol: "AEE", name: "Ameren Corporation", asset_class: "equities" },
  { symbol: "FE", name: "FirstEnergy Corp", asset_class: "equities" },
  { symbol: "CMS", name: "CMS Energy", asset_class: "equities" },
  { symbol: "PPL", name: "PPL Corporation", asset_class: "equities" },
  { symbol: "CNP", name: "CenterPoint Energy", asset_class: "equities" },
  { symbol: "NI", name: "NiSource Inc", asset_class: "equities" },
  { symbol: "EVRG", name: "Evergy Inc", asset_class: "equities" },
  { symbol: "ATO", name: "Atmos Energy", asset_class: "equities" },
  { symbol: "LNT", name: "Alliant Energy", asset_class: "equities" },
  { symbol: "NRG", name: "NRG Energy", asset_class: "equities" },
  { symbol: "VST", name: "Vistra Corp", asset_class: "equities" },
  { symbol: "CEG", name: "Constellation Energy", asset_class: "equities" },
  // Real Estate
  { symbol: "PLD", name: "Prologis Inc", asset_class: "equities" },
  { symbol: "AMT", name: "American Tower", asset_class: "equities" },
  { symbol: "EQIX", name: "Equinix Inc", asset_class: "equities" },
  { symbol: "CCI", name: "Crown Castle", asset_class: "equities" },
  { symbol: "PSA", name: "Public Storage", asset_class: "equities" },
  { symbol: "SPG", name: "Simon Property Group", asset_class: "equities" },
  { symbol: "O", name: "Realty Income", asset_class: "equities" },
  { symbol: "DLR", name: "Digital Realty Trust", asset_class: "equities" },
  { symbol: "WELL", name: "Welltower Inc", asset_class: "equities" },
  { symbol: "VICI", name: "VICI Properties", asset_class: "equities" },
  { symbol: "AVB", name: "AvalonBay Communities", asset_class: "equities" },
  { symbol: "EQR", name: "Equity Residential", asset_class: "equities" },
  { symbol: "ARE", name: "Alexandria Real Estate", asset_class: "equities" },
  { symbol: "MAA", name: "Mid-America Apartment", asset_class: "equities" },
  { symbol: "WY", name: "Weyerhaeuser Company", asset_class: "equities" },
  { symbol: "INVH", name: "Invitation Homes", asset_class: "equities" },
  { symbol: "ESS", name: "Essex Property Trust", asset_class: "equities" },
  { symbol: "UDR", name: "UDR Inc", asset_class: "equities" },
  { symbol: "KIM", name: "Kimco Realty", asset_class: "equities" },
  { symbol: "REG", name: "Regency Centers", asset_class: "equities" },
  { symbol: "BXP", name: "BXP Inc", asset_class: "equities" },
  { symbol: "HST", name: "Host Hotels & Resorts", asset_class: "equities" },
  { symbol: "CPT", name: "Camden Property Trust", asset_class: "equities" },
  { symbol: "FRT", name: "Federal Realty Investment", asset_class: "equities" },
  { symbol: "SBA", name: "SBA Communications", asset_class: "equities" },
  // Additional S&P 500 (cross-sector)
  { symbol: "PLTR", name: "Palantir Technologies", asset_class: "equities" },
  { symbol: "PYPL", name: "PayPal Holdings", asset_class: "equities" },
  { symbol: "SQ", name: "Block Inc", asset_class: "equities" },
  { symbol: "SHOP", name: "Shopify Inc", asset_class: "equities" },
  { symbol: "SNOW", name: "Snowflake Inc", asset_class: "equities" },
  { symbol: "UBER", name: "Uber Technologies", asset_class: "equities" },
  { symbol: "LYFT", name: "Lyft Inc", asset_class: "equities" },
  { symbol: "COIN", name: "Coinbase Global", asset_class: "equities" },
  { symbol: "ZS", name: "Zscaler Inc", asset_class: "equities" },
  { symbol: "DDOG", name: "Datadog Inc", asset_class: "equities" },
  { symbol: "NET", name: "Cloudflare Inc", asset_class: "equities" },
  { symbol: "WDAY", name: "Workday Inc", asset_class: "equities" },
  { symbol: "TEAM", name: "Atlassian Corporation", asset_class: "equities" },
  { symbol: "TTD", name: "The Trade Desk", asset_class: "equities" },
  { symbol: "VEEV", name: "Veeva Systems", asset_class: "equities" },
  { symbol: "ANSS", name: "ANSYS Inc", asset_class: "equities" },
  { symbol: "FICO", name: "Fair Isaac Corporation", asset_class: "equities" },
  { symbol: "SMCI", name: "Super Micro Computer", asset_class: "equities" },
  { symbol: "ARM", name: "Arm Holdings", asset_class: "equities" },
  { symbol: "MRVL", name: "Marvell Technology", asset_class: "equities" },
  { symbol: "MDB", name: "MongoDB Inc", asset_class: "equities" },
  { symbol: "SPLK", name: "Splunk Inc", asset_class: "equities" },
  { symbol: "OKTA", name: "Okta Inc", asset_class: "equities" },
  { symbol: "ZM", name: "Zoom Video Communications", asset_class: "equities" },
  { symbol: "RIVN", name: "Rivian Automotive", asset_class: "equities" },
  { symbol: "LCID", name: "Lucid Group", asset_class: "equities" },
  { symbol: "ENPH", name: "Enphase Energy", asset_class: "equities" },
  { symbol: "SEDG", name: "SolarEdge Technologies", asset_class: "equities" },
  { symbol: "RUN", name: "Sunrun Inc", asset_class: "equities" },
  { symbol: "ANET", name: "Arista Networks", asset_class: "equities" },
  { symbol: "DELL", name: "Dell Technologies", asset_class: "equities" },
  { symbol: "WDC", name: "Western Digital", asset_class: "equities" },
  { symbol: "STX", name: "Seagate Technology", asset_class: "equities" },
  { symbol: "LULU", name: "Lululemon Athletica", asset_class: "equities" },
  { symbol: "CPNG", name: "Coupang Inc", asset_class: "equities" },
  { symbol: "DASH", name: "DoorDash Inc", asset_class: "equities" },
  { symbol: "RBLX", name: "Roblox Corporation", asset_class: "equities" },
  { symbol: "ROKU", name: "Roku Inc", asset_class: "equities" },
  { symbol: "PINS", name: "Pinterest Inc", asset_class: "equities" },
  { symbol: "SNAP", name: "Snap Inc", asset_class: "equities" },
  { symbol: "U", name: "Unity Software", asset_class: "equities" },
  { symbol: "PATH", name: "UiPath Inc", asset_class: "equities" },
  { symbol: "CFLT", name: "Confluent Inc", asset_class: "equities" },
  { symbol: "CRSP", name: "CRISPR Therapeutics", asset_class: "equities" },
  { symbol: "CELH", name: "Celsius Holdings", asset_class: "equities" },
  { symbol: "TOST", name: "Toast Inc", asset_class: "equities" },
  { symbol: "APP", name: "AppLovin Corporation", asset_class: "equities" },
  { symbol: "IOT", name: "Samsara Inc", asset_class: "equities" },
  { symbol: "DUOL", name: "Duolingo Inc", asset_class: "equities" },
];

// Extended crypto beyond existing BTC/ETH/SOL
const CRYPTO: TickerSeed[] = [
  { symbol: "DOGE", name: "Dogecoin", asset_class: "crypto", aliases: ["dogecoin", "doge"] },
  { symbol: "ADA", name: "Cardano", asset_class: "crypto", aliases: ["cardano"] },
  { symbol: "XRP", name: "Ripple", asset_class: "crypto", aliases: ["ripple", "xrp"] },
  { symbol: "DOT", name: "Polkadot", asset_class: "crypto", aliases: ["polkadot"] },
  { symbol: "AVAX", name: "Avalanche", asset_class: "crypto", aliases: ["avalanche"] },
  { symbol: "LINK", name: "Chainlink", asset_class: "crypto", aliases: ["chainlink"] },
  { symbol: "MATIC", name: "Polygon", asset_class: "crypto", aliases: ["polygon", "matic"] },
  { symbol: "UNI", name: "Uniswap", asset_class: "crypto", aliases: ["uniswap"] },
  { symbol: "AAVE", name: "Aave", asset_class: "crypto", aliases: ["aave"] },
  { symbol: "ATOM", name: "Cosmos", asset_class: "crypto", aliases: ["cosmos"] },
  { symbol: "NEAR", name: "NEAR Protocol", asset_class: "crypto", aliases: ["near protocol"] },
  { symbol: "APT", name: "Aptos", asset_class: "crypto", aliases: ["aptos"] },
  { symbol: "ARB", name: "Arbitrum", asset_class: "crypto", aliases: ["arbitrum"] },
  { symbol: "OP", name: "Optimism", asset_class: "crypto", aliases: ["optimism"] },
  { symbol: "SUI", name: "Sui", asset_class: "crypto", aliases: ["sui"] },
  { symbol: "FTM", name: "Fantom", asset_class: "crypto", aliases: ["fantom"] },
  { symbol: "ICP", name: "Internet Computer", asset_class: "crypto", aliases: ["internet computer"] },
  { symbol: "RENDER", name: "Render Token", asset_class: "crypto", aliases: ["render"] },
  { symbol: "INJ", name: "Injective", asset_class: "crypto", aliases: ["injective"] },
  { symbol: "TIA", name: "Celestia", asset_class: "crypto", aliases: ["celestia"] },
];

// Sector ETFs
const SECTOR_ETFS: TickerSeed[] = [
  { symbol: "XLV", name: "Health Care Select Sector ETF", asset_class: "equities" },
  { symbol: "XLU", name: "Utilities Select Sector ETF", asset_class: "equities" },
  { symbol: "XLY", name: "Consumer Discretionary ETF", asset_class: "equities" },
  { symbol: "XLC", name: "Communication Services ETF", asset_class: "equities" },
  { symbol: "XLB", name: "Materials Select Sector ETF", asset_class: "equities" },
  { symbol: "XLI", name: "Industrials Select Sector ETF", asset_class: "equities" },
  { symbol: "XLRE", name: "Real Estate Select Sector ETF", asset_class: "equities" },
  { symbol: "XLP", name: "Consumer Staples ETF", asset_class: "equities" },
  { symbol: "XLF", name: "Financial Select Sector ETF", asset_class: "equities" },
  { symbol: "XLK", name: "Technology Select Sector ETF", asset_class: "equities" },
];

// Macro indices
const MACRO: TickerSeed[] = [
  { symbol: "VIX", name: "CBOE Volatility Index", asset_class: "macro", aliases: ["vix", "volatility index", "fear index"] },
  { symbol: "DXY", name: "US Dollar Index", asset_class: "macro", aliases: ["dollar index", "dxy"] },
  { symbol: "TNX", name: "10-Year Treasury Yield", asset_class: "macro", aliases: ["10 year", "ten year yield"] },
];

const ALL_TICKERS: TickerSeed[] = [...SP500, ...CRYPTO, ...SECTOR_ETFS, ...MACRO];

async function seedSP500Tickers() {
  console.log(`Preparing to seed ${ALL_TICKERS.length} tickers...\n`);

  // Fetch existing tickers for dedup
  const { data: existing, error: fetchError } = await supabase
    .from("tickers")
    .select("symbol");

  if (fetchError) {
    console.error("Failed to fetch existing tickers:", fetchError);
    process.exit(1);
  }

  const existingSymbols = new Set((existing || []).map((t: any) => (t.symbol as string).toUpperCase()));
  console.log(`Found ${existingSymbols.size} existing tickers\n`);

  // Filter out duplicates
  const newTickers = ALL_TICKERS.filter(t => !existingSymbols.has(t.symbol.toUpperCase()));
  console.log(`${newTickers.length} new tickers to insert (${ALL_TICKERS.length - newTickers.length} already exist)\n`);

  if (newTickers.length === 0) {
    console.log("Nothing to insert.");
    return;
  }

  // Batch insert in groups of 20
  const BATCH_SIZE = 20;
  let inserted = 0;
  let failed = 0;

  for (let i = 0; i < newTickers.length; i += BATCH_SIZE) {
    const batch = newTickers.slice(i, i + BATCH_SIZE);
    const rows = batch.map(t => ({
      symbol: t.symbol,
      name: t.name,
      asset_class: t.asset_class,
      aliases: t.aliases || [],
    }));

    const results = await Promise.allSettled(
      rows.map(row =>
        supabase.from("tickers").insert(row as any).select()
      )
    );

    for (let j = 0; j < results.length; j++) {
      const result = results[j]!;
      const ticker = batch[j]!;
      if (result.status === "fulfilled" && !(result.value as any).error) {
        inserted++;
      } else {
        const err = result.status === "rejected" ? result.reason : (result.value as any).error?.message;
        console.error(`  Failed: ${ticker.symbol} — ${err}`);
        failed++;
      }
    }

    console.log(`  Batch ${Math.floor(i / BATCH_SIZE) + 1}/${Math.ceil(newTickers.length / BATCH_SIZE)}: processed ${batch.length} tickers`);
  }

  console.log(`\nDone! Inserted: ${inserted}, Failed: ${failed}, Skipped (existing): ${ALL_TICKERS.length - newTickers.length}`);
  console.log(`Total tickers in database: ~${existingSymbols.size + inserted}`);
}

seedSP500Tickers().catch(console.error);
