-- Ticker digest summaries generated by AI (DeepSeek)
-- Stores per-ticker narrative summaries for each time window

CREATE TABLE IF NOT EXISTS ticker_digests (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  ticker_symbol TEXT NOT NULL REFERENCES tickers(symbol),
  summary TEXT NOT NULL,
  sentiment_avg REAL,
  source_count INTEGER,
  mention_count INTEGER,
  window_start TIMESTAMPTZ NOT NULL,
  window_end TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_ticker_digests_symbol ON ticker_digests(ticker_symbol, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_ticker_digests_window ON ticker_digests(window_end DESC);
