export const minimal = {
  name: 'minimal',
  label: 'Minimal/Clean',
  description: 'Apple-inspired with generous whitespace',
  colors: {
    '--demo-background': '0 0% 98%',
    '--demo-foreground': '0 0% 9%',
    '--demo-card': '0 0% 100%',
    '--demo-card-foreground': '0 0% 9%',
    '--demo-primary': '221 83% 53%',
    '--demo-primary-foreground': '0 0% 100%',
    '--demo-secondary': '0 0% 96%',
    '--demo-secondary-foreground': '0 0% 9%',
    '--demo-accent': '0 0% 96%',
    '--demo-accent-foreground': '0 0% 9%',
    '--demo-muted': '0 0% 96%',
    '--demo-muted-foreground': '0 0% 45%',
    '--demo-border': '0 0% 90%',
    '--demo-input': '0 0% 90%',
    '--demo-ring': '221 83% 53%',
    '--demo-bullish': '142 71% 45%',
    '--demo-bearish': '0 84% 60%',
    '--demo-destructive': '0 84% 60%',
    '--demo-destructive-foreground': '0 0% 100%',
  },
  effects: {
    glow: false,
    blur: false,
    scanlines: false,
    borderRadius: '12px',
    fontFamily: "-apple-system, BlinkMacSystemFont, 'SF Pro Display', sans-serif",
    shadow: '0 1px 3px rgba(0,0,0,0.08)',
  },
};
